# ./config/keywords.yaml
keywords:
  - indoor environmental quality
  - IEQ
  - IEQ monitoring
  - thermal comfort
  - indoor air quality
  - IAQ
  - user behavior modelling
  - CO2
  - CO2 distribution
  - occupancy detection
  - sensor
